usb: gadget: Fix unused-function warning
../../../../../../kernel/xiaomi/sdm845/drivers/usb/gadget/configfs.c:1525:12: error: unused function 'configfs_composite_setup' [-Werror,-Wunused-function]
static int configfs_composite_setup(struct usb_gadget *gadget,
           ^
../../../../../../kernel/xiaomi/sdm845/drivers/usb/gadget/configfs.c:1550:13: error: unused function 'configfs_composite_disconnect' [-Werror,-Wunused-function]
static void configfs_composite_disconnect(struct usb_gadget *gadget)
            ^
Change-Id: I48e85098063cb6fa14fb91f2a08ba0c2ae5cbb2d