techpack: merged audio
Squashed commit of the following:

commit 73ccef74f1b9f2a6e61047345f2f6b335ba36ac2
Author: Nathan Chancellor <natechancellor@gmail.com>
Date:   Sat May 19 11:04:51 2018 -0700

    techpack: build all drivers into the kernel image

    Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>
    Signed-off-by: Park Ju Hyung <qkrwngud825@gmail.com>
    Signed-off-by: awkoo <awkooox@gmail.com>

commit 8fcec12c313561cbb2d40abceac19e93113b979a
Author: PainKiller3 <ninadpatil100@gmail.com>
Date:   Thu Aug 6 21:45:02 2020 +0530

    techpack/audio: Silence unused declarations

    ../techpack/audio/ipc/apr.c:699:14: warning: unused variable 'ptr' [-Wunused-variable]
                            uint32_t *ptr = data.payload;

    Change-Id: I26f9ccbd9833acc42758cb5f3decb303af250875
    Signed-off-by: awkoo <awkooox@gmail.com>

commit d4caace56bf57a00ead856398beb9b5239d9ba5d
Author: Chenyang Zhong <zhongcy95@gmail.com>
Date:   Mon Aug 31 17:34:24 2020 -0400

    techpack: asoc: do not -Wall in the Elliptic ultrasound driver

    The -Wall re-enables some warnings disabled in the parent Makefile.

    Signed-off-by: Chenyang Zhong <zhongcy95@gmail.com>
    Change-Id: I4c7f9a079c9acce0bc4f13610f7a2eadba803485
    Signed-off-by: awkoo <awkooox@gmail.com>

commit f60bd9ad7103f92baa0de142d6483465a9aa0c34
Author: Michael Bestas <mkbestas@lineageos.org>
Date:   Sun Oct 13 16:42:43 2024 +0300

    dsp: q6voice: Switch to __builtin_add_overflow

    As seen on newer kernels

    Change-Id: I87f0a408c211f956ebe8acaf23cbdd8c89fef9e5
    Signed-off-by: awkoo <awkooox@gmail.com>

commit 89fabdabc702f186c552e66e9218e24b90281848
Author: Michael Bestas <mkbestas@lineageos.org>
Date:   Thu Oct 10 16:49:37 2024 +0300

    Merge tag 'LA.UM.8.3.c25-09700-sdm845.0' of https://git.codelinaro.org/clo/la/platform/vendor/opensource/audio-kernel into android13-4.9-sdm845

    "LA.UM.8.3.c25-09700-sdm845.0"

    * tag 'LA.UM.8.3.c25-09700-sdm845.0' of https://git.codelinaro.org/clo/la/platform/vendor/opensource/audio-kernel:
      dsp: q6voice: Adds checks for an integer overflow
      dsp: q6lsm: Address use after free for mmap handle
      ASoC: msm-pcm-host-voice: Check validity of session idx
      ASoC: msm-pcm-voip: Avoid interger underflow
      ASoC: msm-pcm-voip: Avoid interger underflow
      ASoC: msm-pcm-host-voice: Address buffer overflow in hpcm capture copy
      dsp: add change to enable preemption at cal_utils_dealloc_cal.
      dsp: add change to handle use-after-free in cal_utils_is_cal_stale

     Conflicts:
    	techpack/audio/asoc/msm-pcm-host-voice-v2.c
    	techpack/audio/asoc/msm-pcm-voip-v2.c

    Change-Id: Ia26d572cbea1cacdca69055aedcf631e8541689a
    Signed-off-by: awkoo <awkooox@gmail.com>

commit 23a8cba4d2a267a26344cf59bd774c7646ddb9d0
Author: Soumya Managoli <quic_c_smanag@quicinc.com>
Date:   Fri Jan 6 14:37:20 2023 +0530

    BACKPORT: ASoC: msm-pcm-q6-v2: Add dsp buf check

    Current logic copies user buf size of data
    from the avail dsp buf at a given offset.
    If this offset returned from DSP in READ_DONE event
    goes out of bounds or is corrupted, then it can lead to
    out of bounds DSP buffer access, resulting in memory fault.
    Fix is to add check for this buf offset, if it is within
    the buf size range.

    Original-Change-Id: I7753cc6db394704dbb959477150141d42b836bef
    Signed-off-by: Soumya Managoli <quic_c_smanag@quicinc.com>

    (cherry-picked from 28658bc2a0a290fdfcab61bed67e89874e99ca47)
    [ Re-picking to adapt 1ee23bd8c37d for dsp buf check ]
    Change-Id: Ie028d928492e5d113285416226abbeee8e6bfc20
    Signed-off-by: Han Sol Jin <hansol@hansol.ca>
    Signed-off-by: awkoo <awkooox@gmail.com>

commit ba5bf3f818814ac1aa6760ffe539c98a96c64cf9
Author: Laxminath Kasam <lkasam@codeaurora.org>
Date:   Wed Jan 20 11:17:22 2021 +0530

    asoc: Update copy_to_user to requested buffer size

    Avoid copy to user more than requested buffer size
    to avoid memory corruption.

    Change-Id: Ibf1607f777a358ebd16fd8b8728809afda34eba7
    Signed-off-by: Laxminath Kasam <lkasam@codeaurora.org>
    Signed-off-by: awkoo <awkooox@gmail.com>

commit d6d410df037d7c948dcef9c79ed2cbfe00ce38ba
Author: Laxminath Kasam <lkasam@codeaurora.org>
Date:   Fri Oct 16 17:53:22 2020 +0530

    asoc: msm-pcm-q6-v2: Update memset for period size

    tinycap test can attempt with different size to
    read from driver and need to avoid access more
    than period size.

    Change-Id: Ifa4ddfb086bd83aa981da62e88da3a9395f5aabc
    Signed-off-by: Laxminath Kasam <lkasam@codeaurora.org>
    Signed-off-by: awkoo <awkooox@gmail.com>

commit 83d413d77035707d3e5ce0576a55d675cda6fe79
Author: Laxminath Kasam <lkasam@codeaurora.org>
Date:   Thu Jul 9 19:36:36 2020 +0530

    asoc: Reset the buffer if size is partial or zero

    Sometimes during device switch in recording,
    observe size 0 is return from DSP due to EOS
    handling. For ALSA pcm_read to unblock, buffer
    appl_ptr is elapsed without actually updating
    the buffer. And userspace copies the stale
    data(old buffer) causing issue sometimes.
    Reset the buffer for that period_size in
    such cases instead of transfer stale data.

    Change-Id: I0d3ac133a8d95fad0710586e3e947410a41c9c5a
    Signed-off-by: Laxminath Kasam <lkasam@codeaurora.org>
    Signed-off-by: awkoo <awkooox@gmail.com>

commit e298e8b86b45ebf86e2446724d6703ce5dc24bb4
Author: Nathan Chancellor <natechancellor@gmail.com>
Date:   Sat Sep 28 18:42:01 2019 -0700

    ASoC: wcd_cpe_core: Fix buffer overflow in wcd_cpe_init

    Clang warns:

    ../techpack/audio/asoc/codecs/wcd_cpe_core.c:1981:2: warning: 'snprintf'
    size argument is too large; destination buffer has size 11, but size
    argument is 13 [-Werror,-Wfortify-source]
            snprintf(proc_name, (sizeof("cpe") + sizeof("_state") +
            ^
    1 warning generated.

    Fixes: 8e2277f79f0f ("audio-lnx: Initial change for techpack of audio
    drivers.")
    Change-Id: Ide9f1ba2b854ca854918f8ebfd22f8d24c12164b
    Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>
    Signed-off-by: awkoo <awkooox@gmail.com>

commit 2dc1ab1c74edecfbbeb609cc0563fd8ec63e6531
Author: siimsek <malisimsek17@gmail.com>
Date:   Sun Sep 18 03:24:02 2022 -0400

    ASoC: wcd_cpe: Fix enum-conversion warnings

    techpack/audio/asoc/codecs/wcd_cpe_services.c:658:17: error: implicit
    conversion from enumeration type 'enum cpe_svc_result' to different
    enumeration type 'enum cmi_api_result' [-Werror,-Wenum-conversion]
            notif.result = result;
                         ~ ^~~~~~
    techpack/audio/asoc/codecs/wcd_cpe_services.c:1350:8: error: implicit
    conversion from enumeration type 'enum cpe_svc_result' to different
    enumeration type 'enum cpe_process_result' [-Werror,-Wenum-conversion]
                    rc = cpe_send_msg_to_inbox(t_info, 0, m);
                       ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    2 errors generated.

    Change-Id: Ib9fce60017066e9c96e79195d7dba9ffb9177148
    Signed-off-by: awkoo <awkooox@gmail.com>

commit c481374e5afb2d52bb6f6bd302cd42f2d0200799
Author: Soumya Managoli <quic_c_smanag@quicinc.com>
Date:   Thu Jul 20 14:40:44 2023 +0530

    dsp: q6lsm: Address use after free for mmap handle

    The global declared mmap_handle can be left dangling
    for case when the handle is freed by the calling function.
    Fix is to address this. Also add a check to make sure
    the mmap_handle is accessed legally.

    Change-Id: I367f8a41339aa0025b545b125ee820220efedeee
    Signed-off-by: Soumya Managoli <quic_c_smanag@quicinc.com>
    Signed-off-by: awkoo <awkooox@gmail.com>

commit be95a337b663b3ee499c9fd0d5533616a7389476
Author: Soumya Managoli <quic_c_smanag@quicinc.com>
Date:   Mon Jul 31 14:26:42 2023 +0530

    ASoC: msm-pcm-host-voice: Check validity of session idx

    Added check for voice session index.

    Change-Id: Ifff36add5d62f2fdc3395de1447075d297f2c2df
    Signed-off-by: Soumya Managoli <quic_c_smanag@quicinc.com>
    Signed-off-by: awkoo <awkooox@gmail.com>

commit b0f4345d09a451da1498bdef3704939e21ade737
Author: Soumya Managoli <quic_c_smanag@quicinc.com>
Date:   Tue May 30 13:07:18 2023 +0530

    ASoC: msm-pcm-voip: Avoid interger underflow

    There is no check for voip pkt pkt_len,if it contains the
    minimum required data. This can lead to integer underflow.
    Add check for the same.

    Change-Id: I91d4f2ad8dfb060cdb2ab9e36dc9f886ea40908a
    Signed-off-by: Soumya Managoli <quic_c_smanag@quicinc.com>
    Signed-off-by: awkoo <awkooox@gmail.com>

commit b560be961218eedf1572c3f5eb8ea532cb1b3dab
Author: Soumya Managoli <quic_c_smanag@quicinc.com>
Date:   Fri May 26 10:27:32 2023 +0530

    ASoC: msm-pcm-host-voice: Address buffer overflow in hpcm copy

    Add check for the max hpcm_buf_node size before copy to avoid
    buffer out of bounds issue.

    Change-Id: Id647888430ce302359a857ef54d321bee99889bf
    Signed-off-by: Soumya Managoli <quic_c_smanag@quicinc.com>
    Signed-off-by: awkoo <awkooox@gmail.com>

Change-Id: I35bf6a33c938965f7fd68356ad3bd574b1b16720
Signed-off-by: awkoo <awkooox@gmail.com>